"""DAI.BackendGenerator — generate FastAPI routers for departments."""
from __future__ import annotations

from pathlib import Path
from textwrap import dedent
from typing import Any, Dict, List

from dai.core import Registry


class BackendGenerator:
    """Creates FastAPI router files and registration hooks for a department."""

    def __init__(self, *, registry: Registry, base_dir: Path) -> None:
        self.registry = registry
        self.base = base_dir

    def generate(self, dept_name: str, **ctx: Any) -> Dict[str, Any]:
        api_dir = self.base / "api" / dept_name.lower()
        api_dir.mkdir(parents=True, exist_ok=True)
        files_created: List[str] = []
        endpoints: List[Dict[str, str]] = []

        # Package init
        init_path = api_dir / "__init__.py"
        init_path.write_text(
            f'"""API routers for the {dept_name} department."""\n',
            encoding="utf-8",
        )
        files_created.append(str(init_path))

        # Main router
        router_path = api_dir / "router.py"
        router_path.write_text(
            self._render_router(dept_name),
            encoding="utf-8",
        )
        files_created.append(str(router_path))

        slug = dept_name.lower()
        endpoints.extend([
            {"method": "GET", "path": f"/api/{slug}/status", "description": f"{dept_name} status"},
            {"method": "POST", "path": f"/api/{slug}/command", "description": f"Send command to {dept_name}"},
            {"method": "POST", "path": f"/api/{slug}/ux-event", "description": f"UX event from {dept_name} frontend"},
            {"method": "GET", "path": f"/api/{slug}/subais", "description": f"List {dept_name} Sub-AIs"},
        ])

        # Registration helper
        reg_path = api_dir / "register.py"
        reg_path.write_text(
            self._render_register(dept_name),
            encoding="utf-8",
        )
        files_created.append(str(reg_path))

        # Register endpoints in the registry
        for ep in endpoints:
            self.registry.register_endpoint(dept_name, ep)

        return {
            "endpoints": endpoints,
            "files_created": files_created,
        }

    def _render_router(self, dept_name: str) -> str:
        slug = dept_name.lower()
        return dedent(f'''\
            """FastAPI router for the {dept_name} department.

            Auto-generated by DAI.BackendGenerator.
            """
            from __future__ import annotations

            from typing import Any, Dict

            from fastapi import APIRouter

            router = APIRouter(prefix="/api/{slug}", tags=["{dept_name}"])


            @router.get("/status")
            async def get_status() -> Dict[str, Any]:
                """Return current {dept_name} department status."""
                return {{
                    "department": "{dept_name}",
                    "status": "online",
                    "subais": [],
                }}


            @router.post("/command")
            async def post_command(body: Dict[str, Any]) -> Dict[str, Any]:
                """Send a command to {dept_name}. UX -> DAI routing."""
                return {{
                    "department": "{dept_name}",
                    "command": body.get("command", ""),
                    "result": "accepted",
                }}


            @router.post("/ux-event")
            async def post_ux_event(body: Dict[str, Any]) -> Dict[str, Any]:
                """Receive UX events from the {dept_name} frontend. DAI -> UX response."""
                return {{
                    "department": "{dept_name}",
                    "event": body.get("event", ""),
                    "ack": True,
                }}


            @router.get("/subais")
            async def list_subais() -> Dict[str, Any]:
                """List Sub-AIs registered under {dept_name}."""
                return {{
                    "department": "{dept_name}",
                    "subais": [],
                }}
        ''')

    def _render_register(self, dept_name: str) -> str:
        slug = dept_name.lower()
        return dedent(f'''\
            """Auto-register {dept_name} router with the main FastAPI app.

            Usage:
                from api.{slug}.register import register
                register(app)
            """
            from __future__ import annotations

            from fastapi import FastAPI

            from api.{slug}.router import router


            def register(app: FastAPI) -> None:
                """Mount the {dept_name} department router on the given app."""
                app.include_router(router)
        ''')
