"""DAI.SubAIGenerator — generate Sub-AI modules for a department."""
from __future__ import annotations

from pathlib import Path
from textwrap import dedent
from typing import Any, Dict, List

from dai.core import Registry

DEFAULT_CAPABILITIES = ["reasoning", "planning", "execution", "memory", "tools"]


class SubAIGenerator:
    """Creates Sub-AI Python files and registers them in the system map."""

    def __init__(self, *, registry: Registry, base_dir: Path) -> None:
        self.registry = registry
        self.base = base_dir

    def generate(self, dept_name: str, **ctx: Any) -> Dict[str, Any]:
        dept_dir = self.base / "dai" / "departments" / dept_name.lower()
        subais_dir = dept_dir / "subais"
        subais_dir.mkdir(parents=True, exist_ok=True)

        subai_names: List[str] = ctx.get("subais", ["Planner", "Executor", "Monitor"])
        files_created: List[str] = []
        qualified_names: List[str] = []

        # Package init
        init_path = subais_dir / "__init__.py"
        init_path.write_text(
            f'"""Sub-AIs for the {dept_name} department."""\n',
            encoding="utf-8",
        )
        files_created.append(str(init_path))

        for subai_name in subai_names:
            qualified = f"{dept_name}.{subai_name}"
            qualified_names.append(qualified)

            filename = f"subai_{subai_name.lower()}.py"
            filepath = subais_dir / filename
            filepath.write_text(
                self._render_subai(dept_name, subai_name),
                encoding="utf-8",
            )
            files_created.append(str(filepath))

        return {
            "subais": qualified_names,
            "files_created": files_created,
        }

    def _render_subai(self, dept_name: str, subai_name: str) -> str:
        return dedent(f'''\
            """Sub-AI: {dept_name}.{subai_name}

            Auto-generated by DAI.SubAIGenerator.
            Implement the capability stubs below to activate this Sub-AI.
            """
            from __future__ import annotations

            from typing import Any, Dict, List


            class {subai_name}SubAI:
                """Sub-AI for the {dept_name} department: {subai_name}."""

                name = "{dept_name}.{subai_name}"
                department = "{dept_name}"

                # --- reasoning -------------------------------------------------------
                def reason(self, context: Dict[str, Any]) -> Dict[str, Any]:
                    """Analyze inputs and form conclusions."""
                    raise NotImplementedError

                # --- planning --------------------------------------------------------
                def plan(self, goal: str, context: Dict[str, Any]) -> List[str]:
                    """Break a goal into ordered steps."""
                    raise NotImplementedError

                # --- execution -------------------------------------------------------
                def execute(self, step: str, context: Dict[str, Any]) -> Dict[str, Any]:
                    """Execute a single plan step. Returns result dict."""
                    raise NotImplementedError

                # --- memory ----------------------------------------------------------
                def remember(self, key: str, value: Any) -> None:
                    """Store a fact in Sub-AI memory."""
                    raise NotImplementedError

                def recall(self, key: str) -> Any:
                    """Retrieve a stored fact."""
                    raise NotImplementedError

                # --- tools -----------------------------------------------------------
                def available_tools(self) -> List[str]:
                    """Return tool names this Sub-AI can invoke."""
                    return []

                def invoke_tool(self, tool_name: str, **kwargs: Any) -> Any:
                    """Invoke a registered tool by name."""
                    raise NotImplementedError
        ''')
